version: "3"

services:
  ubuntu:
    build: .
    stdin_open: true
    tty: true
    volumes:
      - ./tests:/home/selenium/tests
    depends_on:
      - selenium
      - novnc
    networks:
      - selenium-net

  novnc:
    image: javanile/novnc
    environment:
      - REMOTE_HOST=selenium
      - REMOTE_PORT=5900
    ports:
      - "8081:8081"
    networks:
      - selenium-net

  selenium:
    image: selenium/standalone-chrome:latest
    environment:
      - VNC_NO_PASSWORD=1
      - SCREEN_WIDTH=1800
      - SCREEN_HEIGHT=960
    ports:
      - "4444:4444"
      - "5900:5900"
    networks:
      - selenium-net

networks:
  selenium-net:
